export const activitiesData = {
  activities: [
    {
      id: 1,
      name: "Landing Page Responsive",
      dueDate: "2025-01-04",
      minGrade: 4,
      professorId: 1,
      description: "Desarrollar una landing page responsiva que se adapte a diferentes tamaños de pantalla utilizando HTML, CSS y JavaScript. Debe ser visualmente atractiva y tener una buena experiencia de usuario en dispositivos móviles, tablets y computadoras de escritorio.",
    },
    {
      id: 2,
      name: "API REST con Express",
      dueDate: "2025-01-15",
      minGrade: 6,
      professorId: 1,
      description: "Implementar una API REST utilizando Express.js con endpoints para CRUD de usuarios y autenticación JWT. Debe incluir validación de datos y manejo de errores.",
    },
    {
      id: 3,
      name: "Aplicación React",
      dueDate: "2025-02-01",
      minGrade: 7,
      professorId: 2,
      description: "Crear una aplicación web con React que consuma una API externa. Debe implementar gestión de estado, routing y formularios controlados.",
    },
    {
      id: 4,
      name: "Base de Datos MySQL",
      dueDate: "2025-02-15",
      minGrade: 5,
      professorId: 2,
      description: "Diseñar e implementar una base de datos relacional para un sistema de gestión de biblioteca. Incluir consultas complejas y procedimientos almacenados.",
    },
    {
      id: 5,
      name: "Testing con Jest",
      dueDate: "2025-03-01",
      minGrade: 6,
      professorId: 1,
      description: "Escribir pruebas unitarias y de integración utilizando Jest para una aplicación existente. Debe alcanzar una cobertura mínima del 80%.",
    },
    {
      id: 6,
      name: "Docker y Microservicios",
      dueDate: "2025-03-15",
      minGrade: 8,
      professorId: 3,
      description: "Containerizar una aplicación utilizando Docker y desplegarla en un clúster de microservicios. Implementar comunicación entre servicios.",
    },
    {
      id: 7,
      name: "Seguridad Web",
      dueDate: "2025-04-01",
      minGrade: 7,
      professorId: 3,
      description: "Implementar medidas de seguridad en una aplicación web existente. Proteger contra XSS, CSRF y SQL Injection.",
    },
    {
      id: 8,
      name: "Angular Dashboard",
      dueDate: "2025-04-15",
      minGrade: 6,
      professorId: 2,
      description: "Desarrollar un dashboard administrativo utilizando Angular con gráficos interactivos y gestión de datos en tiempo real.",
    },
    {
      id: 9,
      name: "Cloud Computing AWS",
      dueDate: "2025-05-01",
      minGrade: 7,
      professorId: 3,
      description: "Desplegar una aplicación en AWS utilizando servicios como EC2, S3 y RDS. Implementar auto-scaling y balanceo de carga.",
    },
    {
      id: 10,
      name: "Progressive Web App",
      dueDate: "2025-05-15",
      minGrade: 5,
      professorId: 1,
      description: "Convertir una aplicación web existente en una PWA. Implementar service workers y funcionalidad offline.",
    },
    {
      id: 11,
      name: "GraphQL API",
      dueDate: "2025-06-01",
      minGrade: 8,
      professorId: 2,
      description: "Desarrollar una API GraphQL con Apollo Server. Implementar queries, mutations y resolvers complejos.",
    },
    {
      id: 12,
      name: "CI/CD Pipeline",
      dueDate: "2025-06-15",
      minGrade: 6,
      professorId: 3,
      description: "Configurar un pipeline de CI/CD utilizando GitHub Actions. Automatizar testing, building y deployment.",
    },
    {
      id: 13,
      name: "Kotlin Android App",
      dueDate: "2025-07-01",
      minGrade: 7,
      professorId: 1,
      description: "Crear una aplicación Android nativa con Kotlin. Implementar Material Design y consumo de APIs.",
    },
    {
      id: 14,
      name: "Vue.js E-commerce",
      dueDate: "2025-07-15",
      minGrade: 6,
      professorId: 2,
      description: "Desarrollar una tienda online con Vue.js. Implementar carrito de compras y proceso de checkout.",
    },
    {
      id: 15,
      name: "Machine Learning",
      dueDate: "2025-08-01",
      minGrade: 8,
      professorId: 3,
      description: "Implementar un modelo de machine learning para análisis de sentimientos utilizando TensorFlow.js.",
    }
  ]
};